name:                haskmavlink
version:             0.1.0.0
github:              "sweewarman/haskmavlink"
license:             BSD3
author:              "Swee Warman"
maintainer:          "sweewarman@gmail.com"
copyright:           "2019 Swee Warman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A haskell implementation for the mavlink protocol
# category:            comm protocol, UAV

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sweewarman/haskmavlink#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- hexpat
- containers
- strings
- network
- directory
- optparse-applicative

library:
  source-dirs: 
    - src 

executables:
  mavgen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskmavlink

tests:
  haskmavlink-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
